#!/usr/bin/python3

import pymysql

# 打开数据库连接
db = pymysql.connect(host='10.10.1.145',
                     user = 'root',
                     password = '',
                     port = 3306,
                     db = 'HSS',
                     charset = 'utf8'
                     )

# 使用 cursor() 方法创建一个游标对象 cursor
cursor = db.cursor()
sql = "select * from APN_SELECTION"

# 使用 execute()  方法执行 SQL 查询
cursor.execute(sql)

# 使用 fetchone() 方法获取单条数据.
data = cursor.fetchall()
for i in data[:20]:
    print(i)

cursor.close()
